port: 9090
# 数据库配置
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: dg_hwb_plantform
  username: root
  password: 123456
  charset: utf8mb4
  loc: Asia/Shanghai

# local configuration
local:
  path: 'uploads/file' # 访问路径
  store-path: 'uploads/file' # 存储路径
  expires-time: 2592000 # 上传文件预命名缓存时间(秒)
  
# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''
#加密字段的盐值和长度
hashids:
  salt: 543707aa0df562c8
  minLength: 10
uploadTicket:
  url: 'http://19.1.1.3:84/bhw/req/bhwLandfill/eventRcv/getLandfillJson'